#!/usr/bin/env bash
# pings an IP address passed as an argument

if [ $# -eq 0 ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

IP_ADDRESS=$1

echo "Pinging $IP_ADDRESS..."
ping -c 5 "$IP_ADDRESS"