#!/usr/bin/env bash
# Check for correct number of arguments

if [[ $# -ne 1 ]]; then
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
fi

# Function to start the process
start_process() {
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process started"
}

# Function to stop the process
stop_process() {
    if test -f "/var/run/my_process.pid"; then
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

# Function to restart the process
restart_process() {
    if test -f "/var/run/my_process.pid"; then
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
    fi
    sleep 1
    ./manage_my_process & echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
}

# Check command-line argument
case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac