#!/usr/bin/env bash
# Function to handle SIGTERM signal

handle_sigterm() {
    echo "I am invincible!!!"
}

# Register the handler for SIGTERM
trap handle_sigterm SIGTERM

# Main loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
