#!/usr/bin/env bash
# specify the output

LOGFILE="apache-access.log"

# Use awk to extract IP and HTTP status code, count occurrences, and sort

awk '{ print $1 " " $9}' $LOGFILE | sort | uniq -c | sort -rn