#!/usr/bin/env bash
# specify the number of occurence

LOGFILE="apache-access.log"

# Use awk to extract IP and HTTP status code, count occurrences, and sort
awk '{count[$1" "$9]++} END {for (key in count) print count[key], key}' "$LOGFILE" \
| awk '{print $1, $2, $3}' \
| sort -nr
