#!/usr/bin/env bash
# bad luck 4 and 8

n=1
display="Best School"

while [ $n -le 10 ]; do
    if [ $n -eq 4 ]; then
        echo "bad luck"
    elif [ $n -eq 8 ]; then
        echo "good luck"
    else
        echo "$display"
    fi
    n=$(( n+1 ))
done
