#!/usr/bin/env bash
# display 1 - 20, 4, 7 and 17 special characters

n=1

while [ $n -le 20 ]; do
    if [ $n -eq 4 ]; then
        echo $n
        echo "bad luck from China"
    elif [ $n -eq 9 ]; then
        echo $n
        echo "bad luck from Japan"
    elif [ $n -eq 17 ]; then
        echo $n
        echo "bad luck from Italy"
    else
        echo $n
    fi
    n=$(( n+1 ))
done
