#!/usr/bin/env bash
# configure an Ubuntu Server

# Make a copy of the hosts file
cp /etc/hosts /etc/hosts.new

# Replace the IP address for localhost
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts.new

# Add the entry for facebook.com
echo "8.8.8.8 facebook.com" >> /etc/hosts.new

# Replace the original hosts file with the new one
cp -f /etc/hosts.new /etc/hosts
