#!/bin/bash
# run nginx as nginx
useradd -r -d /var/www -s /sbin/nologin nginx || true
sed -i.bak 's/^user .*/user nginx/; s/listen 80;/listen 8080/' /etc/nginx/nginx.conf
chown -R nginx:nginx /var/lib/nginx /var/log/nginx /var/www
nginx -s reload
